//
// Created by OfferleA on 5/29/2024.
//

#ifndef ARKANOID_CONSTANT_H
#define ARKANOID_CONSTANT_H

#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 624
#define PLAYABLE_ZONE_WIDTH_START 16
#define PLAYABLE_ZONE_HEIGHT_START 16
#define PLAYABLE_ZONE_WIDTH 432
#define PLAYABLE_ZONE_HEIGHT 624

#define MAX_POWERUPS 10

#include <SDL2/SDL.h>



#endif //ARKANOID_CONSTANT_H
