//
// Created by OfferleA on 5/29/2024.
//

#ifndef ARKANOID_CONSTANT_H
#define ARKANOID_CONSTANT_H

#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 640
#define PLAYABLE_ZONE_WIDTH 416
#define PLAYABLE_ZONE_HEIGHT 640

#define MAX_POWERUPS 10

#include <SDL2/SDL.h>



#endif //ARKANOID_CONSTANT_H
